version: '3.8'

services:
  nodebook:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount notebooks directory (create it if it doesn't exist)
      - ./notebooks:/app/notebooks
      # Optional: Mount specific notebook examples
      # - ./test/fixtures/notebooks:/app/notebooks/examples:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nodebook-network

  # Optional: Web proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - nodebook
  #   networks:
  #     - nodebook-network

networks:
  nodebook-network:
    driver: bridge

volumes:
  notebooks:
    driver: local